name: implicit_q_learning
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.12
  - absl-py=2.1.0
  - bcrypt=3.2.0
  - blinker=1.4
  - certifi=2020.6.20
  - cffi=1.16.0
  - click=8.0.3
  - cloudpickle=3.0.0
  - colorama=0.4.4
  - contourpy=1.2.1
  - cryptography=3.4.8
  - cycler=0.12.1
  - Cython=0.29.37
  - d3rlpy=2.5.0
  - d4rl=1.1
  - dataclasses-json=0.6.7
  - decorator=4.4.2
  - dm-control=1.0.20
  - dm-env=1.6
  - dm-tree=0.1.8
  - docker-pycreds=0.4.0
  - etils=1.7.0
  - filelock=3.14.0
  - flax=0.6.1
  - fonttools=4.53.0
  - fsspec=2024.6.0
  - gast=0.5.4
  - GitPython=3.1.43
  - glfw=2.7.0
  - gym=0.23.0
  - gymnasium=0.29.1
  - h5py=3.11.0
  - imageio=2.34.1
  - imageio-ffmpeg=0.5.1
  - importlib-metadata=4.6.4
  - importlib_resources=6.4.0
  - jax=0.4.1
  - jaxlib=0.4.1+cuda11.cudnn86
  - Jinja2=3.1.4
  - joblib=1.4.2
  - keyring=23.5.0
  - kiwisolver=1.4.5
  - labmaze=1.0.6
  - lazy_loader=0.4
  - lxml=5.2.2
  - Mako=1.1.3
  - matplotlib=3.9.0
  - moviepy=1.0.3
  - mpmath=1.3.0
  - msgpack=1.0.8
  - mujoco=3.1.6
  - mujoco-py=2.1.2.14
  - mypy-extensions=1.0.0
  - netifaces=0.11.0
  - networkx=3.3
  - numpy=1.23.1
  - nvidia-cublas-cu12=12.1.3.1
  - nvidia-cuda-cupti-cu12=12.1.105
  - nvidia-cuda-nvrtc-cu12=12.1.105
  - nvidia-cuda-runtime-cu12=12.1.105
  - nvidia-cudnn-cu12=8.9.2.26
  - nvidia-cufft-cu12=11.0.2.54
  - nvidia-curand-cu12=10.3.2.106
  - nvidia-cusolver-cu12=11.4.5.107
  - nvidia-cusparse-cu12=12.1.0.106
  - nvidia-nccl-cu12=2.20.5
  - nvidia-nvjitlink-cu12=12.5.40
  - nvidia-nvtx-cu12=12.1.105
  - oauthlib=3.2.0
  - opencv-python=4.10.0.84
  - opt-einsum=3.3.0
  - optax=0.1.3
  - packaging=24.1
  - paramiko=2.9.3
  - pillow=10.3.0
  - pip=24.1
  - pre-commit=3.3.3
  - proglog=0.1.10
  - promise=2.3
  - protobuf=3.20.3
  - psutil=5.9.0
  - pybullet=3.2.6
  - pycairo=1.20.1
  - pycparser=2.22
  - pygame=2.1.0
  - Pygments=2.18.0
  - PyNaCl=1.5.0
  - PyOpenGL=3.1.7
  - pyparsing=3.1.2
  - pyrallis=0.3.1
  - python-dateutil=2.8.1
  - pytz=2022.1
  - PyYAML=5.4.1
  - requests=2.25.1
  - rich=13.7.1
  - ruff=0.0.278
  - scikit-image=0.24.0
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - setuptools=59.6.0
  - six=1.16.0
  - smmap=5.0.1
  - structlog=24.2.0
  - sympy=1.12.1
  - tensorboardX=2.6.2.2
  - termcolor=2.4.0
  - threadpoolctl=3.5.0
  - tifffile=2024.6.18
  - toolz=0.12.1
  - torch=1.11.0+cu113
  - tqdm=4.64.0
  - triton=2.3.1
  - typing_extensions=4.12.2
  - typing-inspect=0.9.0
  - wandb=0.12.21
  - wheel=0.37.1
  - xdg=5
  - zipp=1.0.0
