cg_damping: 0.5
checkpoints_path: /project_data/held/sreyas/RL-VLM-F/gail/PassWater/GAIL--seed-42-softgym_PassWater-756a3d6a
data_set_path: /project_data/held/sreyas/data/datagen/PassWater/datagen_PassWater-Medium-10000/PassWater-medium.pkl
device: cuda
env: softgym_PassWater
epsilon: 0.05
eval_freq: 500
eval_iter: 10
gae_gamma: 0.99
gae_lambda: 0.99
group: metaworld
horizon: null
lambda_: 0.01
load_model: ''
lr: 5.0e-05
max_kl: 0.05
n_episodes: 10
name: GAIL--seed-42-softgym_PassWater-756a3d6a
normalize: true
normalize_advantage: true
normalize_reward: false
num_iters: 300
num_samples: 1024
policy_update_freq: 2
project: ICRA2024-PassWater-medium-10K
render: true
seed: 42
