cg_damping: 0.5
checkpoints_path: /project_data/held/sreyas/RL-VLM-F/gail/debug/GAIL--seed-43-CartPole-v1-d13b18d8
data_set_path: /project_data/held/sreyas/data/datagen/Cartpole/datagen_Cartpole-Expert/Cartpole-expert.pkl
device: cuda
env: CartPole-v1
epsilon: 0.05
eval_freq: 500
eval_iter: 10
gae_gamma: 0.99
gae_lambda: 0.99
group: metaworld
horizon: null
lambda_: 0.01
load_model: ''
lr: 5.0e-05
max_kl: 0.05
n_episodes: 10
name: GAIL--seed-43-CartPole-v1-d13b18d8
normalize: true
normalize_advantage: true
normalize_reward: false
num_iters: 300
num_samples: 1024
policy_update_freq: 2
project: debug_
render: true
seed: 43
